Feature/temperature: Ambient temperature pipeline
spacesys-finch/payload-designer pull request #75
Opened 2022-03-06 18:22 UTC by rararani

2022-03-08 19:14 UTC, DM1122 requested changes
Solid progress! Great idea to create a base component class to house the operating temp ranges. Was going to get around to it eventually, glad you got it done. Later on, mass and volume envelopes will be stored as attributes in the base class to reduce redundancy.

2022-03-08 19:14 UTC, DM1122 commented on payload_designer/pipelines/pipe_ambient_temp.py
> +    )
This algorithm assumes all the temperature ranges are overlapping, which might not be the case. Check out the attached document which shows some possible range cases. There's some logic that's needed to determine what this function should do in each of them. This reminds me of a typical interview technical question.

[FINCH Operating Temperature Ranges by Component Cases.pdf](https://github.com/spacesys-finch/payload-designer/files/8208902/FINCH.Operating.Temperature.Ranges.by.Component.Cases.pdf)

2022-03-08 23:40 UTC, rararani commented on payload_designer/components/lenses.py
> +from lib2to3.pytree import Base
Sometimes VSCode auto imports randoms stuff. It must've saw "Base" and decided to auto import this library lol, I'll remove it

2022-03-11 02:12 UTC, rararani commented on payload_designer/pipelines/pipe_ambient_temp.py
> +    ]
@DM1122 what is the focuser here? It's defined the same way as the collimator.

2022-05-01 21:01 UTC, DM1122 commented on payload_designer/pipelines/pipe_ambient_temp.py
> +    ]
The focuser is the exact same lens component as the the collimator. They're just two of the same lenses in different parts of the track. The collimator makes the incident light parallel to itself, the collimator focuses the parallel light onto the sensor face.

2022-05-01 21:01 UTC, DM1122 approved these changes

2022-05-01 21:02 UTC, merged